version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - databases:/var/lib/mysql

  app:
    build: .
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html"]
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: root
      DB_PASSWORD: ""

volumes:
  databases:
